// Code written by Gabriel Mailhot, 02/06/2026.
// Sprint 12b: NPC-initiated letter correspondence.
// Sprint 12d: reply courier support (DispatchDay, CourierPartyId, IsLost).

namespace NpcMemoryService.Core.Models
{
   /// <summary>
   ///   A letter sent (or queued to be sent) from an NPC to the player. Stored on the
   ///   sending NPC's <see cref="NpcProfile.SentLetters"/> list so the entire
   ///   correspondence history lives alongside the NPC's identity.
   ///
   ///   Lifecycle: Generated (LLM call) → in transit (<see cref="IsDelivered"/> false)
   ///   → delivered (popup shown, <see cref="IsDelivered"/> true) → optionally replied
   ///   to (<see cref="PlayerReply"/> set), which triggers a new letter from the NPC.
   /// </summary>
   public sealed class PendingLetter
   {
      /// <summary>Hero StringId of the NPC who wrote the letter.</summary>
      public string? SenderId { get; set; }

      /// <summary>Display name of the sender — stable even if the hero is later dead.</summary>
      public string? SenderName { get; set; }

      /// <summary>Why the NPC chose to write. Drives the generation prompt and categorisation.</summary>
      public LetterReason Reason { get; set; }

      /// <summary>The full letter text as generated by the LLM.</summary>
      public string? Content { get; set; }

      /// <summary>In-game day the letter was composed (generation triggered).</summary>
      public int SentOnDay { get; set; }

      /// <summary>
      ///   In-game day the letter is due to arrive. Calculated from the distance between
      ///   the sender and the player at the time of sending.
      /// </summary>
      public int DeliveryDay { get; set; }

      /// <summary>True once the popup has been shown and the player acknowledged or replied.</summary>
      public bool IsDelivered { get; set; }

      /// <summary>
      ///   The player's reply text, if they chose to respond. When set, the delivery
      ///   service triggers a new LLM call to generate the NPC's next letter.
      /// </summary>
      public string? PlayerReply { get; set; }

      /// <summary>
      ///   Sprint 12d — Day the reply courier should depart. Zero for NPC-initiated
      ///   letters (dispatched immediately). For <see cref="LetterReason.PlayerLetterReply" />
      ///   letters this is set to <c>decisionDay + chosenDelay</c> by the LLM; the
      ///   courier only spawns when <c>today >= DispatchDay</c> on the main thread.
      /// </summary>
      public int DispatchDay { get; set; }

      /// <summary>
      ///   Sprint 12d — <c>MobileParty.StringId</c> of the visible reply courier.
      ///   Null until the courier spawns; cleared once delivered or lost.
      /// </summary>
      public string? CourierPartyId { get; set; }

      /// <summary>Sprint 12d — true when the reply courier was destroyed in transit.</summary>
      public bool IsLost { get; set; }

      /// <summary>
      ///   True once an <see cref="LetterReason.AwaitingReply"/> follow-up has been
      ///   queued for this unanswered letter. Stored on the original letter so the guard
      ///   survives even when the follow-up placeholder is later removed (LLM failure or
      ///   session-reload orphan cleanup).
      /// </summary>
      public bool FollowUpSent { get; set; }
   }
}
